version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "products-app"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-1uvhaxrsuc1zy"
s3_prefix = "products-app"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
image_repositories = []
